export const JOURNALISTS = [
  'Nina Hart',
  'Marcus Vale',
  'Rhea Collins',
  'Devon Price',
  'Talia Monroe',
  'Grant Mercer',
  'Selena Pierce',
  'Owen Barrett',
]

export const NEWSPAPERS = [
  'The Turnbuckle Gazette',
  'Daily Grapple',
  'Ringline Tribune',
  'Arena Financial Post',
  'Pro Wrestling Ledger',
  'The Kayfabe Chronicle',
  'Matside Journal',
  'Squared Circle Sentinel',
]

export const HIRE_QUESTION_TEMPLATES = [
  'You recently signed #{latestHire}. What was your strategy behind hiring him?',
  'What role do you expect #{latestHire} to play in #{companyName} over the next few weeks?',
  'Was #{latestHire} signed for immediate impact, or as a long-term project?',
  'How does #{latestHire} change your current locker room chemistry?',
  'What convinced you that #{latestHire} was worth the contract commitment?',
  'Did #{latestHire} fit a gap in your roster, or did you sign him because of upside?',
  'How do you plan to introduce #{latestHire} to your fanbase of #{fans}?',
  'Will #{latestHire} be pushed quickly, or developed step by step?',
  'What internal metrics did you review before signing #{latestHire}?',
  'Do you see #{latestHire} entering title contention soon, or building momentum first?',
  'How did your coaching team evaluate #{latestHire} before finalizing the deal?',
  'Was #{latestHire} your first-choice target, or a strategic pivot?',
  'What risk did you accept by committing to #{latestHire}?',
  'How does #{latestHire} align with your current prestige level of #{prestige}?',
  'What feedback have you heard from veterans about signing #{latestHire}?',
  'Do you plan to pair #{latestHire} with a manager early on?',
  'How do you balance hype and patience in the early booking of #{latestHire}?',
  'Will #{latestHire} be featured on #{upcomingEvent}, or eased in first?',
  'How does the signing of #{latestHire} affect opportunities for current talent?',
  'What did negotiation with #{latestHire} teach you about your hiring process?',
  'Was fan demand part of your decision to sign #{latestHire}?',
  'How quickly do you expect #{latestHire} to improve match quality?',
  'What would make the signing of #{latestHire} a success by week #{week}?',
  'Did you target #{latestHire} for in-ring ability, star power, or both?',
  'How does #{latestHire} fit your broader roster identity right now?',
  'What concerns did you have before approving the contract for #{latestHire}?',
  'Do you expect #{latestHire} to help grow fans beyond #{fans} in the short term?',
  'How much creative freedom will #{latestHire} have in his character direction?',
  'Could signing #{latestHire} influence your title plans for #{currentTitle}?',
  'If #{latestHire} struggles early, how patient will you remain as a booker?',
]

export const MATCH_QUESTION_TEMPLATES = [
  'Your last featured match involved #{latestMatchParticipants}. What was your takeaway?',
  'How do you assess #{latestMatchWinner} after that recent result?',
  'Was the #{latestMatchRating} rating from your recent match fair in your view?',
  'What did your locker room learn from the match featuring #{latestMatchParticipants}?',
  'Did the recent result for #{latestMatchWinner} change your booking plans?',
  'How do you respond to criticism about pacing in your latest match card?',
  'Were you satisfied with the storytelling in your last major segment?',
  'What one thing from the last card would you improve immediately?',
  'Did your recent match outcomes match your internal expectations?',
  'How did crowd energy affect performance in your latest show?',
  'Do you think your recent winners are ready for higher stakes now?',
  'How are you preventing rematches from feeling repetitive?',
  'What did you learn about talent endurance from your latest card?',
  'Did any undercard performer exceed your expectations recently?',
  'How are you balancing short-term results with long-term stories?',
  'Were there any production decisions in the last show you regret?',
  'How much does match quality drive your week-to-week direction?',
  'Did your latest results reinforce your current hierarchy or challenge it?',
  'How do you evaluate chemistry between opponents after each event?',
  'What did your match agents report after the latest event?',
  'Are you seeing clear progress in in-ring execution over recent weeks?',
  'How do you decide whether to continue a feud after one major match?',
  'Did you intentionally book surprises in your most recent card?',
  'How do you use recent match analytics in planning the next show?',
  'What is your biggest concern coming out of the latest in-ring performances?',
  'Do recent outcomes suggest a shift in your main-event scene?',
  'How are you protecting wrestlers from overexposure in recent bookings?',
  'What role did fan reaction play in your recent booking decisions?',
  'Do recent match results change who might challenge for #{currentTitle}?',
  'How do you keep match variety high across consecutive events?',
]

export const UPCOMING_EVENT_QUESTION_TEMPLATES = [
  'Looking ahead to #{upcomingEvent}, what is your top booking priority?',
  'What should fans expect to feel differently at #{upcomingEvent}?',
  'How much pressure do you feel heading into #{upcomingEvent}?',
  'Will #{upcomingEvent} focus on spectacle, in-ring quality, or both?',
  'How are you structuring the card for #{upcomingEvent} right now?',
  'Do you already know your main event for #{upcomingEvent}?',
  'What would make #{upcomingEvent} a clear success in your eyes?',
  'How are you building anticipation for #{upcomingEvent} this week?',
  'Will #{upcomingEvent} feature a major debut or surprise?',
  'How does #{upcomingEvent} fit your season-long narrative?',
  'Are you taking creative risks at #{upcomingEvent} or playing it safe?',
  'What challenge worries you most before #{upcomingEvent}?',
  'How are you balancing veteran stars and newer faces at #{upcomingEvent}?',
  'Could #{upcomingEvent} reshape your title scene for #{currentTitle}?',
  'How much of #{upcomingEvent} is locked versus still flexible?',
  'Do sponsorship obligations influence planning for #{upcomingEvent}?',
  'Will #{upcomingEvent} prioritize grudge matches or championship stories?',
  'How are you preparing talent mentally for #{upcomingEvent}?',
  'What production element are you emphasizing at #{upcomingEvent}?',
  'Are there matchups you are avoiding at #{upcomingEvent} to save for later?',
  'How does fan momentum of #{fans} impact decisions for #{upcomingEvent}?',
  'Do you expect #{upcomingEvent} to raise your prestige above #{prestige}?',
  'How important is card balance at #{upcomingEvent} from open to close?',
  'What is your contingency plan if injuries affect #{upcomingEvent}?',
  'Is #{upcomingEvent} built around one story or multiple equal arcs?',
  'How are you managing expectations from media before #{upcomingEvent}?',
  'Will #{upcomingEvent} include a breakout opportunity for newer talent?',
  'How are you deciding which rivalries peak at #{upcomingEvent}?',
  'What message do you want #{upcomingEvent} to send about #{companyName}?',
  'Could #{upcomingEvent} be the turning point of your current year?',
]

export const FINANCE_QUESTION_TEMPLATES = [
  'With current cash at #{cash}, what is your immediate financial priority?',
  'How do you balance payroll commitments against event investment?',
  'What spending category are you monitoring most tightly right now?',
  'Are you currently in growth mode or cost-control mode financially?',
  'How does your fan base of #{fans} influence your revenue planning?',
  'What financial lesson have you learned most recently as a promoter?',
  'Do you prefer investing in star signings or production upgrades first?',
  'How do you evaluate return on investment for new contracts?',
  'Is your current budget strategy built for stability or aggressive expansion?',
  'How do event outcomes affect your next-week budgeting decisions?',
  'What is the biggest financial risk in your current plan?',
  'How do you prevent short-term hype spending from hurting long-term health?',
  'What metrics tell you whether your roster costs are sustainable?',
  'Are you satisfied with your current expense-to-revenue balance?',
  'Do you forecast cash flow event by event or over longer windows?',
  'How do sponsorship opportunities influence your spending confidence?',
  'What part of operations has become unexpectedly expensive lately?',
  'How do you set limits when negotiating with high-demand talent?',
  'Would you describe your current financial position as comfortable at #{cash}?',
  'How has recent performance changed your willingness to invest?',
  'Do you keep reserve capital for emergencies, and how much?',
  'How do you decide between marketing spend and roster spend?',
  'What financial target are you trying to hit by week #{week}?',
  'How do you protect profitability while still improving show quality?',
  'Is there one financial decision you would redo if given another chance?',
  'How do title programs impact your revenue expectations?',
  'Do you view your current prestige of #{prestige} as a financial leverage point?',
  'How does attendance volatility affect your budget discipline?',
  'Are you preparing financially for a larger-scale event soon?',
  'How do you communicate budget realities to your creative team?',
]

export const CHAMPION_QUESTION_TEMPLATES = [
  'How do you evaluate #{currentChampion} as the current face of #{currentTitle}?',
  'Is #{currentChampion} the right standard-bearer for this phase of #{companyName}?',
  'What is your plan to keep the #{currentTitle} scene fresh?',
  'Do you prioritize long reigns or frequent title changes right now?',
  'How do you choose challengers for #{currentTitle}?',
  'What traits made #{currentChampion} your ideal champion at this moment?',
  'Are you satisfied with how #{currentChampion} is connecting with fans?',
  'Could #{currentChampion} carry #{upcomingEvent} as a headline attraction?',
  'How do you protect title prestige while still creating surprises?',
  'What is your benchmark for a successful title reign?',
  'Do your champions influence hiring and roster decisions?',
  'How close are you to changing the landscape around #{currentTitle}?',
  'Is there enough depth behind #{currentChampion} for compelling defenses?',
  'How do you keep challengers credible before facing #{currentChampion}?',
  'What does #{currentChampion} still need to prove as champion?',
  'How much freedom does #{currentChampion} have in shaping title stories?',
  'Do you expect the #{currentTitle} division to evolve soon?',
  'How do fan responses shape your champion booking decisions?',
  'Would a shocking title change help or hurt your current momentum?',
  'How important is in-ring consistency for holding #{currentTitle}?',
  'Do you think #{currentChampion} can elevate new opponents effectively?',
  'Is the current title picture aligned with your long-term vision?',
  'How do you avoid making #{currentTitle} feuds feel predictable?',
  'What separates #{currentChampion} from the rest of the contenders?',
  'Could #{upcomingEvent} feature a defining moment for #{currentTitle}?',
  'How do you handle pressure when fans demand a title change?',
  'Does your current champion strategy match your prestige of #{prestige}?',
  'How much does champion marketability factor into your decisions?',
  'What would cause you to pivot away from #{currentChampion}?',
  'How do you keep championship stories emotionally compelling week to week?',
]

export const QUESTION_TEMPLATES = [
  ...HIRE_QUESTION_TEMPLATES,
  ...MATCH_QUESTION_TEMPLATES,
  ...UPCOMING_EVENT_QUESTION_TEMPLATES,
  ...FINANCE_QUESTION_TEMPLATES,
  ...CHAMPION_QUESTION_TEMPLATES,
]